spring.application.name=order_service
server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5432/order_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

catalog.service.url=http://localhost:8081
catalog.service.username=admin
catalog.service.password=admin123

spring.cloud.openfeign.okhttp.enabled=true
spring.cloud.openfeign.httpclient.enabled=false

app.security.users.admin.username=admin
app.security.users.admin.password=admin123
app.security.users.customer.username=user@example.com
app.security.users.customer.password=password
app.security.users.customer2.username=user2@example.com
app.security.users.customer2.password=password
